### ISSUE TITLE
Admin View Volunteer Card Modal

### ISSUE THREAD

**Issue by NwinNwin** [ctc-uci/stand-up-to-trash-frontend#125]
<img src="https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/376058d1-b64c-44e7-8254-ca5bdf17c980" width="400">

## [Link to Figma Component ](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=2325-6955&mode=design&t=EEPOW9qLkgU1nd9T-0)

# Description
## Backend
- Create an new backend endpoint `GET data/volunteer/:volunteerId/event/` in `routes/data.js` to retrieve a list of `events names` the given `volunteerId` attended
- Create an new backend endpoint `GET data/images/:volunteerId/` in `routes/data.js` to retrieve a list of all images url from row `event_data_new` table that has `volunteerId`
  - To do this: use SQL to read the `image_array` column in `event_data_new` table. (each element is the `imageId` in `event_data_images`)
  - Link both table (event_data_new + event_data_images) using JOIN and ONLY return an array of `s3_url` that matches the `imageId` in `image_array`

## Frontend
- Create a component in the picture above ^
- In `Playground.jsx`, create a button to open a new component `VolunteerCardModal.jsx` (you will have to create this)
- This component takes in a `prop` of `volunteerId` (you can put a **hardcoded valid** `volunteerId` in for testing purposes)
- Use this volunteerId to call `GET /profiles/:volunteerId` to get information about the user:
  - first & last name
  - email
  - profile image_url
- Use `GET stats/volunteer/:volunteerId` to get user's `Total Trash`
- Use the list of `events names` from the endpoint you created in the past step to display `Events Attended`
-  Make a TextArea for "Other Information" field. (no functionality for this)
- Use the list of `s3_url` to display images you did in past step.

# Resources
- [FIGMA](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=2325-6955&mode=design&t=EEPOW9qLkgU1nd9T-0)
- Please let us know if you have any question

**Comment by KevinWu098** [comment]
Assigning tasks at 1 AM @NwinNwin 

my tech leads work so hard 🙏

**Comment by NwinNwin** [comment]
![Alt Text](https://media1.tenor.com/m/5deH6fDl8cgAAAAd/radiorazeratrah.gif)
