### ISSUE TITLE
Generate QR Code For Volunteer ID Util + Implement Scanner Functionality

### ISSUE THREAD

**Issue by Aokijiop** [ctc-uci/stand-up-to-trash-frontend#141]
#### Edit (4/3) 3:10 PM: Task has been finalized. Design has agreed to adjust the flow of bringing up the QR Code on the volunteer side. What this means is that the flow will need some time to get revised/finalized by design. As such I have removed the `QRCheckInModal` from the task. <ins>This means the task will just involve adding the scan button to `CheckInPage` and implementing the `Scanner` functionality as specified.</ins>
- To test out the `Scanner`, you can generate a QR code with a valid volunteer ID and try scanning it

# Description
- From the check-in page of a specific event, admins will be able to scan in volunteers to check them in
    - Within the check-in page for every event, there is a blue "scan" button that when selected, will bring up the `Scanner`
        - You can think of it as every event having their own `Scanner` with the event_id passed into `Scanner` as a prop
        - Every volunteer will also have their own QR code which is generated from their volunteer id
        - When the `Scanner` scans a volunteer, it will be able to obtain the volunteer id from the QR code while it already knows the event_id implicitly via the prop
        - After a scan, the `CheckInModal` will be brought up with the correct information 
            - ![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/89126184/a5613221-4e88-43fc-a48c-3e59c189ce53)
            - This is already a component but note that it expects a `volunteer` prop which requires the following information from both users and event_data: first_name, last_name, image_url, number_in_party
            - Preserve the functionality (This is already implemented in `CheckInModal`:
                - Form validation (Can't be submitted unless party size input is filled)
                - Upon submission, overrides the event_data row with the new entered number_in_party
            - Note that the `onCheckInConfirm` prop is the `changeIsCheckedIn` function from the `CheckInPage`
- Edit `CheckInPage` to implement the "scan" button in the bottom right
    - This should be fixed not absolute
    - When pressed, it will bring up `Scanner` with the current event's event_id passed in as a prop
- There is an existing `Scanner` component but it will need modifications
    - Modify the `Scanner` so that it can take in an event_id as a prop
    - After a scan, bring up the `CheckInModal` with the correct information
        - For now, you can safely assume every QR code you scan will be a valid volunteer id
        - Preserve the functionality of the `CheckInModal` as specified above
- Create the `QRCodeCheckInModal` which is the modal that contains the volunteer's QR code that they can show an admin to check in
    - [TBA: waiting on some design questions]
    - The QR code will be generated using the qrcode.react library and is simply a QR code that stores the plain text of the volunteer's id
        - ![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/89126184/de11c2ab-32db-4551-8ec6-4f1f0685d044)

# Acceptance Criteria
- The "scan" button on the `CheckInPage` for each event has been implemented as specified above
- `Scanner` has been modified as specified above
    - `CheckInModal` has its functionality preserved as specified above

# Resources
- [qrcode.react documentation](https://www.npmjs.com/package/qrcode.react)
    - (I kept this in here in case you wnated ot play around with creating/scanning QR codes)
- [Admins Scanning In Volunteers to Check-In Flow](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=1820-14780&mode=design&t=swPhqCFNKZcXksSR-0)

**Comment by KevinWu098** [comment]
When the hell did I lock this issue 💀
