### ISSUE TITLE
Mobile View - Volunteer Current Event Page

### ISSUE THREAD

**Issue by NwinNwin** [ctc-uci/stand-up-to-trash-frontend#168]
# **NOTE**
- Before working on this, use Dimension of an iPhone SE in `inspect element`
![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/258ee526-a1ab-4c95-a45d-733678ee853f)

- [Read Chakra UI Responsive Styles Doc](https://chakra-ui.com/docs/styled-system/responsive-styles)
  - Use `base` and `md` breakpoints
  - Ex: {{base: "0", md: "15rem"}}
  - Base is mobile, md is desktop
  - lmk if u need help on this

# Volunteer Current Page in Mobile View
<img width="230" alt="image" src="https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/2d38147d-de89-4f35-8686-244c131372b8">

- The Volunteer Current Page **Code** is in `pages/VolunteerEventPage.jsx`
- To **View** the Page: 
  - Log in to a Volunteer account --> go to `http://localhost:3000/volunteer-event`
### What it looks like rn in mobile:
  - <img width="281" alt="image" src="https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/e136e2e1-58ed-4b53-92bc-7480f3f14e2e">

# To do:
## Event Card Grid:
- Make the Event Card's Grid displays 1 card per row instead of 4 in **iPhoneView** only
  - Use `base` and `md` break points
- When exiting the `iPhone View` it should return to original

## Feature Events :
![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/5ea9fd2b-5ff2-4fa5-81ff-c5dce3cbcd22)

- Feature Event should only have **1 event** in `iPhone View`
- When exiting `iPhone View`, it should return to original where it has 2 events
- Add `md` breakpoint in order to do this

# Resources:
- Let us know if you have any questions
- [Figma](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?type=design&node-id=3357-15898&mode=design&t=fJRomHqQ3Q1iJuDx-0)

**Comment by eachen1010** [comment]
Should we just copy figma boss

**Comment by NwinNwin** [comment]
ohh im still writing it so its wip rn hehe

**Comment by NwinNwin** [comment]
updated

**Comment by eachen1010** [comment]
goat!!

**Comment by eachen1010** [comment]
goat!!!!
