### ISSUE TITLE
HomePage, PastEvents, ViewEvents Pages: Refactor/Implement Export Button

### ISSUE THREAD

**Issue by Aokijiop** [ctc-uci/stand-up-to-trash-frontend#179]
## It is HIGHLY RECOMMENDED, you examine `CSVExample` and <ins>test the two routes I created</ins> in `stats.js` or completing the task will be extremely difficult!

# Description
- Currently, we have an "Export Data" button located in `HomePage` which generates a CSV file containing all rows from event_data (Joined with events and users for readability)
- The problem with this current "Export Data" button is that it simply dumps all the data from event_data into a CSV which makes it hard to see meaningful stats
- Your first job for this task will be to refactor the "Export Data" button in `HomePage` so that it generates <ins>a CSV file for EVERY event</ins>
    - The data you will use to create these CSV files comes from the route: `/stats/export/data`
        - <ins>You MUST test this route out and view/understand the format of the returned data or completing the task will be impossible!</ins>
- Your second job for this task will be to implement the "Export Data" button for `PastEvents` which is identical to the "ExportData" button in `HomePage` with the added condition that it only generates <ins>a CSV file for EVERY PAST event</ins>
    - The data you will use to create these CSV files comes from the route: `/stats/export/data/past`
        - <ins>Again, you MUST test this route out and view/understand the format of the returned data or completing the task will be impossible!</ins> (It's the same format though)
    - This should almost be a straight copy-paste from `HomePage` with the exception that the data now comes from a different route: `/stats/export/data/past`
- Your third job for this task will be to implement the "Export Data" button for "ViewEvents" which will generate a single CSV for the specified event (Determined by the eventId in `ViewEvents`)
    - Create a new backend route: `/stats/export/data/:eventId`
        - The new route should return data in a format that matches the previous two routes (Picture for reference) but for a specific event id
        - ![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/89126184/64141894-6fb2-4d55-9c64-e585ce305f21)
- To help clarify the task, I have created a `CSVExample` which is an example button placed in `Playground` that when clicked will download a CSV for a single event
    - <ins>This is the expected CSV file format for all 3 parts of the task</ins>
    - I would highly recommend you <ins>reference the code</ins> in `CSVExample`
- This is one of the most confusing tasks I wrote so please Slack me to clarify any questions!

# Acceptance Criteria
- The "Export Data" button in `HomePage` has been refactored as specified
- The "Export Data" button in `PastEvents` has been implemented as specified
- The "Export Data" button in `ViewEvents` has been implemented as specified
    - The new backend route: `/stats/export/data/:eventId` has been created as specified

# Resources
- View `CSVExample`

**Comment by NwinNwin** [comment]
4AM issue is crazy
