### ISSUE TITLE
Leaderboard + Dashboard responsiveness 

### ISSUE THREAD

**Issue by NwinNwin** [ctc-uci/stand-up-to-trash-frontend#202]
<img width="800" alt="image" src="https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/c5f0824b-a468-4ef1-9b42-4384d6e4414c">

# Description:
- Sign in to admin account and Go to `http://localhost:3000/input-data/35`
- Work on `InputDataDashboard.jsx` inside `Input Data Page`
- It looks very ugly rn, made changes to it so it looks like the Figma design
  - <img width="504" alt="image" src="https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/884c854c-a01f-432b-b4a0-9dd5f1a056ee">

- Feel free to fix anything to match the design

# Resources:
- [Figma Link](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-High-Fidelity-Wireframes?node-id=1477-13203&mode=dev)

**Comment by KevinWu098** [comment]
Closed by #204
