### ISSUE TITLE
Implement Authentication with Google and Facebook

### ISSUE THREAD

**Issue by Aokijiop** [ctc-uci/stand-up-to-trash-frontend#55]
# Description
- As of right now, we have the ability to sign-in using an email and password
- We are going to be adding two new sign-in methods: Google and Facebook
    - To do this, we are going to leverage Firebase's implementation of OAuth, which provides helpful built-ins for signing in with both Google and Facebook
    - Fortunately, both methods are very similar
    
- Authentication with Google
    - Create a new file in our frontend utils called `googleAuthUtils.js`
    - Reference the documentation on how to obtain the needed helper functions
    - Use the `signInWithRedirect` method because it is the most compatible for both web and mobile devices
    - Create the following util functions:
        - `createGoogleUserInFirebase`
            - This should use the built-in function `signInWithRedirect`
            - Utilize the `getRedirectResult` to track the signed-in user and to also perform error-handling
                - For now, you can simple store the user in a const
                - For error handling, retrieve the error code and error message and console log them
                    - Annoyingly, the page on the documentation which should show all the error codes is outdated so for now, just log the error code and message
        - `logGoogleUserOut`
            - Very straightforward, just use the `signOut` built-in
            - Perform error handling by catching any errors and then console logging the error code and error message

-  Authentication with Facebook (This is pretty much a copy paste of the Google Auth :P)
    - Create a new file in our frontend utils called `facebookAuthUtils.js`
    - Reference the documentation on how to obtain the needed helper functions
    - Use the `signInWithRedirect` method because it is the most compatible for both web and mobile devices
    - Create the following util functions:
        - `createFacebookUserInFirebase`
            - This should use the built-in function `signInWithRedirect`
            - Utilize the `getRedirectResult` to track the signed-in user and to also perform error-handling
                - For now, you can simple store the user in a const
                - For error handling, retrieve the error code and error message and console log them
                    - Surprise, surprise, the documentation on the error codes is still outdated!
        - `logFacebookUserOut`
            - Very straightforward, just use the `signOut` built-in
            - Perform error handling by catching any errors and then console logging the error code and error message
    - For authenticating with Facebook, this requires a Facebook Developer account. I should have everything set up with all the permissions but if anything is missing, please let me know!

- Matching the hi-fi design for the login, sign up, and forgot password pages
    - We have the following pages: `LoginV2`, `SignupV2`, and `ForgotPasswordV2`
    - Edit the following pages so that they match the hi-fi design
    - Implement the appropriate util functions in the `LoginV2` page to implement logging in with Google and Facebook

# Acceptance Criteria
- The specified util functions have been implemented and utilize the specified built-ins and provide the specified error-handling
- The util functions have been appropriately implemented into the `LoginV2` page

# Resources
- [How to authenticate with Google in Firebase Auth](https://firebase.google.com/docs/auth/web/google-signin)
- [How to authenticate with Facebook in Firebase Auth](https://firebase.google.com/docs/auth/web/facebook-login?authuser=0)
- [Hi-fi Wireframes](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-Hi-Fidelity-Wireframes?type=design&node-id=289-1674&mode=design&t=w5SneIm5QBs2Gjwo-0)

**Comment by KevinWu098** [comment]
Me when auth:

![distintegrate](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/100006999/729d5c29-acde-4b17-a558-c72d0b106349)
