### ISSUE TITLE
Leaderboard Feature + Functionality

### ISSUE THREAD

**Issue by NwinNwin** [ctc-uci/stand-up-to-trash-frontend#73]
![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/93059380/a829a513-0829-4f64-a8ef-83b1101e2d6a)

[Hi-Fi Figma Design](https://www.figma.com/file/wD3jldG53uVqnUYDF5HcSs/Low-Hi-Fidelity-Wireframes?type=design&node-id=814-10414&mode=design&t=LxcAXg84wfnO9wMG-0)

# Description

## Backend (Do this first)
- Implement a new API endpoints `GET /stats/leaderboard` in `stats.js` (backend).
  - This query will search the `event_data` table and find the top 3 volunteer with the highest SUM of trash data.

## Frontend
- Implement your leaderboard in `/playground`
- Coordinate cross-functional engagement with the design team to select the most appropriate leaderboard design. 
  - **talk to gayathri bro**
- Make API call to the backend route (the one you created in backend) to display the leaderboard data.

  ## Resources
- [Database Model](https://www.figma.com/file/SHhIfyH2uo1jIMRFfZkgFz/Database-Model?type=design&node-id=6-1694&mode=design&t=Uc1n3CXtcWUsWOwE-0)
- [Chakra Documentation](https://chakra-ui.com/)

**Comment by eachen1010** [comment]
u fr bro

**Comment by NwinNwin** [comment]
jk bro i need to confirm a few things with design team first. we lyk when done with this.

**Comment by eachen1010** [comment]
u the boss
