### ISSUE TITLE
Connect New Auth Methods to Users Table

### ISSUE THREAD

**Issue by Aokijiop** [ctc-uci/stand-up-to-trash-frontend#87]
# Description
- In `LoginV2`,  there are two new ways of logging: Google and Facebook
- When a user creates an account using these two methods, create functionality to add a new row into our Users table
    - Information you will need:
        - First name and last name
            - Obtainable from the `onAuthStateChanged` observer (The user object in `Playground`)
        - Role (Will always be "volunteer")
        - Email
            - Obtainable from the `onAuthStateChanged` observer (The user object in `Playground`)
        - Firebase UID
            - Obtainable from the `onAuthStateChanged` observer (The user object in `Playground`)
    - It's important to note that our Firebase will <ins>link accounts with the same email</ins> even if different sign-in methods wre used
        - For example, if I use the email osuryaja@uci.edu to create an account using both the plain email/password and Google methods, only one row will appear in our console since the email will be linked
            - ![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/89126184/21834673-41df-4de9-a5d8-9bd0d0776655)
                - Notice how multiple sign-in methods will have both the same email and Firebase UID
        - What this means is that you may not always need to add a new row into our Users table because similarly, we'll hold one row in Users per email
        - So, before adding a new row into Users, check if there is already an existing row in Users that has the Firebase UID of the newly created account
            - If there is, no need to add a new row in Users, it's already there (They already signed up using some other sign-in method)
            - If there isn't, add a new row in Users

# Acceptance Criteria
- For both Google and Facebook sign-in methods, a new row will be added to Users if there is no existing row with a matching Firebase UID of the newly created account
    - If there is an existing row, Users table will be left untouched

# Resources
- If you console.log the user object from the `onAuthStateChanged` observer, you can see some needed fields:
    - ![image](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/89126184/b33fbabe-d800-47d7-9a38-38a66b18c18c)
    - Some important ones:
        - displayName
        - email
        - uid
- [Firebase onAuthStateChanged](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged)

**Comment by Aokijiop** [comment]
Apologies for another auth task @KevinWu098

**Comment by KevinWu098** [comment]
> Apologies for another auth task @KevinWu098

              Me when auth:

![distintegrate](https://github.com/ctc-uci/stand-up-to-trash-frontend/assets/100006999/729d5c29-acde-4b17-a558-c72d0b106349)

_Originally posted by @KevinWu098 in https://github.com/ctc-uci/stand-up-to-trash-frontend/issues/55#issuecomment-1928529958_
